variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"
  NAMESPACE: pyrene-dev
  PROJECT: talos_metapkg_ros_control_sot
  REGISTRY: gepgitlab.laas.fr:4567
  IMAGE: "${REGISTRY}/${NAMESPACE}/${PROJECT}"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache


.robotpkg-talos-metapkg-ros-control-sot: &robotpkg-talos-metapkg-ros-control-sot
  variables:
    ROBOTPKG: talos-metapkg-ros-control-sot
    CATEGORY: wip
  before_script:
    - mkdir -p ccache
  script:
    - cd /root/robotpkg/${CATEGORY}/${ROBOTPKG}
    - git pull
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    
    
  except:
    - gh-pages


robotpkg-talos-metapkg-ros-control-sot-14.04:
  <<: *robotpkg-talos-metapkg-ros-control-sot
  image: ${IMAGE}:14.04


robotpkg-talos-metapkg-ros-control-sot-16.04:
  <<: *robotpkg-talos-metapkg-ros-control-sot
  image: ${IMAGE}:16.04


robotpkg-talos-metapkg-ros-control-sot-dubnium:
  <<: *robotpkg-talos-metapkg-ros-control-sot
  image: ${IMAGE}:dubnium



