sot_controller:
  libname: libsot-pyrene-controller.so
  simulation_mode: gazebo
  joint_names: [ leg_left_1_joint, leg_left_2_joint, leg_left_3_joint, leg_left_4_joint, leg_left_5_joint, leg_left_6_joint,
    leg_right_1_joint, leg_right_2_joint, leg_right_3_joint, leg_right_4_joint, leg_right_5_joint, leg_right_6_joint,
    torso_1_joint,torso_2_joint,
    arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, gripper_left_joint,
    arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, gripper_right_joint,
    head_1_joint, head_2_joint ]
  map_rc_to_sot_device: { motor-angles: motor-angles ,
  joint-angles: joint-angles, velocities: velocities, forces: forces, currents: currents,
  torques: torques, control: control, accelerometer_0: accelerometer_0, gyrometer_0: gyrometer_0 }
  control_mode:
    leg_left_1_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_left_2_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_left_3_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_left_4_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_left_5_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_left_6_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_right_1_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_right_2_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_right_3_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_right_4_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_right_5_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    leg_right_6_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    torso_1_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    torso_2_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_left_1_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_left_2_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_left_3_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_left_4_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_left_5_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_left_6_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_left_7_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    gripper_left_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_right_1_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_right_2_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_right_3_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_right_4_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_right_5_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_right_6_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    arm_right_7_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    gripper_right_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    head_1_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}
    head_2_joint: { ros_control_mode: EFFORT, sot_control_mode: EFFORT}

  dt: 0.001
